### ISSUE TITLE
Logos lack padding on mobile

### ISSUE THREAD

**Issue by nickofbh** [acm-uiuc/rp2016#126]
![image](https://cloud.githubusercontent.com/assets/2055203/18292895/64638c2c-7455-11e6-86b7-2747f61c9649.png)

**Comment by pranaygp** [comment]
This looks fixed. I just tested it on a bunch of mobile and tables devices. 

Can we close this? @sskhandek

**Comment by pranaygp** [comment]
![image](https://cloud.githubusercontent.com/assets/1797812/18368029/6f1f490a-75e3-11e6-90b7-334c57a38f06.png)

**Comment by sskhandek** [comment]
I'm not seeing this either on Android. I'm closing for now
