### ISSUE TITLE
27N/270N Airbus Doesn't Exist Anymore

### ISSUE THREAD

**Issue by nickofbh** [acm-uiuc/rp2016#129]
There's no bus from the airport anymore

**Comment by Salil999** [comment]
These are 2 alternatives:
https://www.iflycu.com/transportation/rentalcars
http://www.urbanaillinois.us/residents/taxicabs-limousines

**Comment by vpahwa** [comment]
Or Uber?

**Comment by sskhandek** [comment]
Easy money for you @redsn0w422

**Comment by redsn0w422** [comment]
PR #202 fixes this.
