### ISSUE TITLE
Viewing a bio dismisses another open bio

### ISSUE THREAD

**Issue by nickofbh** [acm-uiuc/rp2016#130]
See title

**Comment by redsn0w422** [comment]
I think this was an intentional design choice ... @bluedrops

**Comment by bluedrops** [comment]
Yeah, this was an intentional choice; is this unintuitive?
I thought it was a natural assumed behavior but if it's not, I can change it haha

**Comment by sskhandek** [comment]
I think it's fine for now. Closing for now
