### ISSUE TITLE
http://reflectionsprojections.com/jobfair/ needs better styling

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#149]
This is not public facing or advertised just yet, but it needs some styling work.

Also, remove apigee, they aren't coming

cc: @sameetandpotatoes @YashoSharma @pranaygp if any of you want to get creative / claim this

**Comment by redsn0w422** [comment]
Part of this is any links we may include - is their logo a link to their site? do we want a link to their application portal? etc etc.

**Comment by YashoSharma** [comment]
I'd love to take a shot at it

**Comment by sskhandek** [comment]
All yours @YashoSharma

**Comment by sskhandek** [comment]
@YashoSharma did u have any progress here you wanted to submit? I was gonna work on this later

**Comment by YashoSharma** [comment]
@sskhandek No I haven't had a chance to do much yet

**Comment by sskhandek** [comment]
@YashoSharma That's fine. Ill work on it tonight then
