### ISSUE TITLE
Make Right Nav Menu Responsive with a hamburger icon

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#16]
Currently the nav menu isn't responsive and needs to be in a side menu when resizing the window or viewing the site on mobile

**Comment by sskhandek** [comment]
Overall, there's probably a better way to do this menu, but whoever claims this task can get creative. @devinho if you had a chance, this would be a great way to help out.

**Comment by devinho** [comment]
Yep I'll take this :)

**Comment by sskhandek** [comment]
Thanks @devinho !

**Comment by sskhandek** [comment]
Also @devinho, as a side-note, the way we're doing thing is that you can create a branch named after the issue you're addressing, and then push to that branch and then PR.

**Comment by devinho** [comment]
Yep was doing that exact thing. PR for this started at #26
