### ISSUE TITLE
Bug with the icons on the main page. 

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#165]
I think this is a mistake I made, it uses the same style as the twitter icons in the speaker cards

<img width="549" alt="screen shot 2016-09-12 at 9 47 17 am" src="https://cloud.githubusercontent.com/assets/5349493/18440245/f104d1e6-78cd-11e6-8650-0acc869b8767.png">

**Comment by sskhandek** [comment]
@YashoSharma @redsn0w422 @sameetandpotatoes

**Comment by YashoSharma** [comment]
@sskhandek actually the twitter icons in the speaker icons use the same style as it, I can change the card styling if you want
