### ISSUE TITLE
Increase character cap on MechMania school registration

### ISSUE THREAD

**Issue by camcuz97** [acm-uiuc/rp2016#175]
When signing up for the MechMania Hackathon, I ran into an error where I couldn't fit the entire name of UIUC into the registration form. Considering it says full university name AND it's run at UIUC, the character cap should be increased to at least accomodate UIUC's name.
<img width="732" alt="screen shot 2016-09-15 at 3 52 13 pm" src="https://cloud.githubusercontent.com/assets/13397981/18567160/82bb471a-7b5c-11e6-9837-d6b080cb9dd3.png">

**Comment by sskhandek** [comment]
Nice catch. Thank you, we'll update that!

**Comment by sskhandek** [comment]
Fixed @camcuz97
