### ISSUE TITLE
Description Text on Hover in About Section

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#19]
Right now, there are no descriptions on the images in the about section. Preferably, we can implement a design on hover where the user hovers over an image and an opaque black background with text can cover the image.

**Comment by redsn0w422** [comment]
Another option is using Bootstrap tooltips: http://getbootstrap.com/javascript/#tooltips

**Comment by sskhandek** [comment]
I feel like we'll run into a similar problem that the speaker section has right now. Let's put this on hold for now and come up with an overall smarter design.

**Comment by sskhandek** [comment]
Considering the potential re-design of the about section in #33 , this may not be necessary
