### ISSUE TITLE
Remove all job fair logos and assets that aren't being used

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#192]
under jobfair/assets/logos, we have a ton of logos that aren't being used. Please help remove it

**Comment by redsn0w422** [comment]
@sskhandek is there a reason we have duplicate .svg and .png, but are using the .png?

**Comment by sskhandek** [comment]
In my experience of using them on the page, the pngs were better sized / they worked just fine.

**Comment by redsn0w422** [comment]
okay cool I just wanted to make sure they weren't both being used somehow

**Comment by redsn0w422** [comment]
#203 fixes this.
