### ISSUE TITLE
Startup Fair logos look inconsistently sized

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#200]
<img width="412" alt="screen shot 2016-09-20 at 3 17 16 pm" src="https://cloud.githubusercontent.com/assets/5349493/18687363/5c28ee80-7f45-11e6-9de1-e454904f7402.png">

**Comment by sskhandek** [comment]
@YashoSharma I also added you as a collaborator so you can create branches and claim issues lol

**Comment by vgvbach95** [comment]
Ready for review.
