### ISSUE TITLE
Descriptions for special events

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#211]
Let's have descriptions that explain what the special events are.

<img width="1228" alt="screen shot 2016-09-21 at 11 23 55 am" src="https://cloud.githubusercontent.com/assets/5349493/18719673/fbebf6d0-7fed-11e6-8cb0-dfd563ed877c.png">

**Comment by sskhandek** [comment]
@sameetandpotatoes @vpahwa

**Comment by vgvbach95** [comment]
I'll use what's on the facebook pages for these events.
