### ISSUE TITLE
Remove Avant from Startup Fair subpage

### ISSUE THREAD

**Issue by tyler-thetyrant** [acm-uiuc/rp2016#218]
:<

**Comment by bluedrops** [comment]
![](http://i.imgur.com/9v9fLSm.png)

**Comment by tyler-thetyrant** [comment]
![1ee14e148d070ecba6978111a1a9212b](https://cloud.githubusercontent.com/assets/12504517/18721902/3c1c5fa6-7ff8-11e6-8824-d96c59cabeb1.jpg)
