### ISSUE TITLE
Some Startup Fair logos are missing / Logos need to have the company name

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#228]
<img width="999" alt="screen shot 2016-09-21 at 9 55 05 pm" src="https://cloud.githubusercontent.com/assets/5349493/18735763/10f52c24-8046-11e6-93d7-8ad009da324e.png">

<img width="1058" alt="screen shot 2016-09-21 at 9 55 25 pm" src="https://cloud.githubusercontent.com/assets/5349493/18735767/1cd4d238-8046-11e6-8a7d-6c0df321505d.png">

**Comment by tyler-thetyrant** [comment]
I can fix it? If no one is working on it :3

**Comment by tyler-thetyrant** [comment]
Also some logos needs higher res files.

**Comment by sskhandek** [comment]
@tyler-thetyrant if you do this in the next hour, fantastic. Otherwise, I'll do it
