### ISSUE TITLE
Open Graph tags for Facebook

### ISSUE THREAD

**Issue by Salil999** [acm-uiuc/rp2016#233]
This isn't a giant priority, but I think it would be nice to have proper R|P images when sharing the website. I shared the website to a friend at a different school, and it turned out like this: [Sharing Website](http://prnt.sc/ckyctk) (Salesforce is great and all, but so are the other sponsors!)

**Comment by Salil999** [comment]
Facebook's Open Graph Markup documentation: [Webmasters - Sharing](https://developers.facebook.com/docs/sharing/webmasters)

**Comment by vgvbach95** [comment]
Pull request made.

**Comment by sskhandek** [comment]
@vgvbach95 thank you!

**Comment by vgvbach95** [comment]
Image still not showing up.

**Comment by vgvbach95** [comment]
Fixed. Took a minute to update.
