### ISSUE TITLE
Compressed images need to be referenced

### ISSUE THREAD

**Issue by Salil999** [acm-uiuc/rp2016#238]
Compressed images are in the root directory in a folder called (you guessed it) **compressed**. Just need somebody to reference the images in the code. I tried to mirror the same structure as what the current project holds (hence the nesting of the folders)

**Comment by sskhandek** [comment]
@bluedrops ?

**Comment by bluedrops** [comment]
will do fam

**Comment by sskhandek** [comment]
#245 does this for the main page. @Salil999, I think you compressed images earlier than the latest set of changes, especially for startup fair. Can you compress the latest batch of images in those folders?

**Comment by Salil999** [comment]
Can you tell me which directories specifically? Or should I just recompress all of them?

**Comment by Salil999** [comment]
finished!
