### ISSUE TITLE
Subpage for the Video Wall

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#251]

**Comment by redsn0w422** [comment]
I'd like to help with this one, what did you have in mind? A big schedule, with the current item highlighted?

**Comment by sskhandek** [comment]
@redsn0w422 I think Simon's got this one. We had talked out some details earlier and he has a better sense of what needs to go in it. Thanks tho :)

**Comment by bluedrops** [comment]
![](https://dl.dropboxusercontent.com/u/5048629/rp_main.png) 

any changes?
