### ISSUE TITLE
Some sponsor logos are too big

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#27]
Some of the sponsor logos are disproportionately sized and just plain too large. Can we set a max height on the logos?

<img width="1205" alt="screen shot 2016-07-20 at 11 47 15 pm" src="https://cloud.githubusercontent.com/assets/5349493/17013582/584d2caa-4ed4-11e6-8794-ebfc295d657d.png">

**Comment by redsn0w422** [comment]
PR #29 fixes this issue.
