### ISSUE TITLE
Add final speaker from 5 - 5:50 on schedule and speaker cards

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#273]
![unnamed](https://cloud.githubusercontent.com/assets/5349493/18890461/ebdcb0c6-84c6-11e6-912a-c1c41125522b.jpg)

BIO:

Gabrielle Allen is a Professor of Astronomy at the University of Illinois Urbana-Champaign and the Associate Director for Computational Research and Education Programs at the National Center for Supercomputing Applications. 

Between 2010 and 2012 Gabrielle served as a Program Director in the Office of Cyberinfrastructure at the National Science Foundation (NSF) in Washington DC. At NSF, Gabrielle developed NSF-wide programs in software and computational and data-enabled science, and within OCI was responsible for learning and workforce development activities including CAREER, REU and the CI-TRACS postdoctoral fellowship program.

In 2012, Gabrielle moved to the Moscow, Russia to become a professor at a new graduate university - the Skolkovo Institute of Science and Technology (Skoltech) - established by the Russian Federation in partnership with MIT. Here, she worked primarily on establishing the IT and cyberinfrastructure vision for Skoltech as the interim Chief Information Officer. In 2014 Gabrielle moved to the University of Illinois Urbana-Champaign.

**Comment by sskhandek** [comment]
The bio is rather long, so please CUT

**Comment by pranaygp** [comment]
We should add a facebook event for this for consistency: https://www.facebook.com/acmrp/events

**Comment by sskhandek** [comment]
Sure but let's get this up first. I'll have our social media person do that

**Comment by YashoSharma** [comment]
5-50 on Friday correct?
