### ISSUE TITLE
About Section Re-design

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#33]
<img width="1307" alt="screen shot 2016-07-21 at 11 16 15 pm" src="https://cloud.githubusercontent.com/assets/5349493/17048228/2c63a590-4f99-11e6-852d-062101adab61.png">

Simply put, this is ugly. A nice redesign would be awesome

**Comment by sskhandek** [comment]
cc'ing @devinho & @vpahwa for some input or suggestions

**Comment by sskhandek** [comment]
https://www-s.acm.illinois.edu/conference/2014/ cut down on the wording a lot and didn't include images. We can also change the background from being fixed here

**Comment by vpahwa** [comment]
Maybe if you hover over them, you get text? That would look cool. Or maybe
a carousel of these images?

On Fri, Jul 22, 2016 at 1:59 AM, Sujay Khandekar <notifications@github.com>
wrote:

> https://www-s.acm.illinois.edu/conference/2014/ cut down on the wording a
> lot and didn't include images. We can also change the background from being
> fixed here
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_acm-2Duiuc_rp2016_issues_33-23issuecomment-2D234469312&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=3seeSafke-tC9EDnLd8kSj_Y7VsnfKHmu_U519QLlzQ&m=iOu4aNbTy-ATgA9cx5Q9wtc5wCdCOteanOolQ_KNBTg&s=La7j5kQ4JWhz8bL1xc5t1aEKKmAn0qTFRVbdXnF4Ldk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIZ9WCSNoCcjcjtJKe2v-2DpbmYId0xEmXks5qYGphgaJpZM4JSeHG&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=3seeSafke-tC9EDnLd8kSj_Y7VsnfKHmu_U519QLlzQ&m=iOu4aNbTy-ATgA9cx5Q9wtc5wCdCOteanOolQ_KNBTg&s=hZFc5v7rapck4hsqYiSGAzSH5ed-M93lCURteiNWG9Y&e=>
> .
>



-- 
Vaibhav Pahwa

*UIUC Computer Science + Statistics 2018*
*Reflections|Projections Co-Chair*
*Freelance Product Manager @ Gigster (YC S15)*

**Comment by devinho** [comment]
I can take a pass on it with sketch. I think the text is fine, just have to find a better way to display it.
