### ISSUE TITLE
Image file sizes are way too large for web

### ISSUE THREAD

**Issue by berwinxie** [acm-uiuc/rp2016#46]
<img width="1440" alt="screen shot 2016-08-07 at 21 49 01" src="https://cloud.githubusercontent.com/assets/5169056/17468819/d99781b2-5ce8-11e6-849d-61037ab844c0.png">

Should not take 4+ seconds to load the page. 5.59MB of files is a lot.

**Comment by sskhandek** [comment]
This is a really good point. We need to also use svgs

**Comment by akleiner2** [comment]
I can (or someone can) take a stab at this later tonight. Would be great to have some sort of build system in place to automatically do this before pushing to GitHub.

**Comment by sskhandek** [comment]
@akleiner2 any recommendations as far as build systems go? I'm all ears. We have the simplest stack right now haha

**Comment by akleiner2** [comment]
@sskhandek Haha it's great. I was just poking around the ACM GH, and would love to help out. I was thinking a simple Gulpfile with tasks for dev + prod I think should do the trick. Thoughts? 

Also, are you guys planning on using SVGs for most things?

**Comment by sskhandek** [comment]
http://pmt.sourceforge.net/pngcrush/

**Comment by Salil999** [comment]
Can also recommend https://tinypng.com

**Comment by sskhandek** [comment]
@Salil999 halp when 374 isn't crushing you :)

**Comment by sskhandek** [comment]
@Salil999 ?

**Comment by Salil999** [comment]
@sskhandek My apologies, 374 + interviews been taking a while. I will have it _finished_ by tonight.

**Comment by sskhandek** [comment]
Thank you @Salil999

**Comment by Salil999** [comment]
Finished & successfully merged! Request to close issue (unless I missed something??)
