### ISSUE TITLE
Speaker card resizing gives different heights

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#50]
<img width="768" alt="screen shot 2016-08-07 at 11 45 22 pm" src="https://cloud.githubusercontent.com/assets/5349493/17471456/12c23ad0-5cf9-11e6-9641-3d6e40453cd7.png">

**Comment by berwinxie** [comment]
Additionally, for some reason when I look at it, the images don't fit into the cards perfectly.

<img width="985" alt="screen shot 2016-08-08 at 9 23 32 am" src="https://cloud.githubusercontent.com/assets/5169056/17485131/ea7c4628-5d49-11e6-843e-43d8e2e68225.png">

**Comment by akleiner2** [comment]
+1 to what @berwinxie said.

**Comment by sskhandek** [comment]
Does #71 help here?

**Comment by berwinxie** [comment]
I don't think it's fixable. I believe that the problem lies in the fact that Bootstrap is responsive and uses non-integer widths to fill in column widths. This causes some imperfect pixel alignments with images and the container.
