### ISSUE TITLE
Update all the job fair companies as of 8/19

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#59]
Please use SVGs
<img width="424" alt="screen shot 2016-08-09 at 11 44 07 pm" src="https://cloud.githubusercontent.com/assets/5349493/17544297/34d491b6-5e8b-11e6-8ba7-87590c79b971.png">

**Comment by tyler-thetyrant** [comment]
![nznrhom](https://cloud.githubusercontent.com/assets/12504517/17618964/77d28d94-6037-11e6-83ee-ac8ee5dfac81.gif)
