### ISSUE TITLE
Responsive - borken

### ISSUE THREAD

**Issue by tyler-thetyrant** [acm-uiuc/rp2016#82]
![screenshot 10](https://cloud.githubusercontent.com/assets/12504517/18061540/b24c0a7c-6de8-11e6-9c6a-29f468e21273.png)

This only happens at a certain width

**Comment by sskhandek** [comment]
Probably one small breakpoint to modify. Thanks

**Comment by sskhandek** [comment]
@bluedrops I think you can fix this?

**Comment by bluedrops** [comment]
@sskhandek Was actually just playing with this earlier, coincidentally! It looks like a bootstrap clearfix issue, but I tried to use clearfix to fix it and it didn't work; I may just switch it to flexbox tonight. Will handle this tonight and submit a PR for it. c:
