### ISSUE TITLE
Nike Logo and Wayfair logos are hard to see

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#84]

**Comment by berwinxie** [comment]
Do you think it would be poor practice to edit their logos by hand, ala

<img width="659" alt="screen shot 2016-08-30 at 11 44 45" src="https://cloud.githubusercontent.com/assets/5169056/18098293/3cba2a2c-6ea7-11e6-80f7-220dbc3299f8.png">

**Comment by sskhandek** [comment]
I think Nike has an alternate white logo like that, so that might be okay, but definitely not for wayfair.

**Comment by ndryden** [comment]
Nike has media resources and logos [here](http://news.nike.com/news/nike-media-resources).

Wayfair does [here](http://www.wayfair.com/v/about/news_room), but they don't seem to have an alternate. I'd ask if they do-- editing or using logos without permission has gotten us nasty emails from company legal teams before.

**Comment by berwinxie** [comment]
I based Wayfair off of this, but just took the other logo since it was low res:

http://wayfair.shop.rakuten.com/RDCSFiles/30885553/Images/buy_wayfair_logo.jpg
