### ISSUE TITLE
Logos are Stretched After Flexbox Change

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#88]
<img width="1072" alt="screen shot 2016-08-31 at 7 13 21 pm" src="https://cloud.githubusercontent.com/assets/5349493/18150773/103f325e-6faf-11e6-82e8-7150b24e582e.png">

**Comment by sskhandek** [comment]
Also the spacing is a bit much. Can we reduce that please?

**Comment by redsn0w422** [comment]
PR #100 fixes this issue for RetailmeNot and Palantir. Still working on the rest of the sponsor logos
