### ISSUE TITLE
Speaker Section

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#9]

**Comment by sskhandek** [comment]
@redsn0w422 , I'm not sure how much work you've done on this, but @modi95 had a good point about modals being kinda hard to view on mobile. He recommended card flipping kinda like what's done here: https://davidwalsh.name/css-flip Thoughts? @vpahwa, any comments?

**Comment by redsn0w422** [comment]
I like the css-flip, I'll work on that. 

@vpahwa is the list of speakers finalized yet?

**Comment by vpahwa** [comment]
Yep, minus one slot

On Thu, Jul 21, 2016 at 10:31 AM, Yasha Mostofi <notifications@github.com>
wrote:

> I like the css-flip, I'll work on that.
>
> @vpahwa
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vpahwa&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=3seeSafke-tC9EDnLd8kSj_Y7VsnfKHmu_U519QLlzQ&m=ZeG0M-FnJ1VKYxV29ViO1ZgosjEunJALa-eCB3QEs5c&s=7q8H-gqf6wg0jl7DXG2Fd83_VpI0W93wwuS4hlmnn-s&e=>
> is the list of speakers finalized yet?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_acm-2Duiuc_rp2016_issues_9-23issuecomment-2D234290959&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=3seeSafke-tC9EDnLd8kSj_Y7VsnfKHmu_U519QLlzQ&m=ZeG0M-FnJ1VKYxV29ViO1ZgosjEunJALa-eCB3QEs5c&s=y3PXOO1idTwbwZqa-XW2caVwscGD8SfQlsafB0k9ZI0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIZ9WBcFyNfhlOo-2DYMU3kjMKl4LUjx3bks5qX5DhgaJpZM4JOITm&d=CwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=3seeSafke-tC9EDnLd8kSj_Y7VsnfKHmu_U519QLlzQ&m=ZeG0M-FnJ1VKYxV29ViO1ZgosjEunJALa-eCB3QEs5c&s=6eM97JMxI8vDh4_Byafn2HKnxXzFzauaGk3Q-SaqYWA&e=>
> .
>



-- 
Vaibhav Pahwa

*UIUC Computer Science + Statistics 2018*
*Reflections|Projections Co-Chair*
*Freelance Product Manager @ Gigster (YC S15)*

**Comment by vpahwa** [comment]
Also @sskhandek @redsn0w422 Flip is sweet, would work nicely on mobile

**Comment by redsn0w422** [comment]
Does that mean the flip would be on tap for mobile, and hover for desktop? Or tap/click on both?

**Comment by vpahwa** [comment]
I like the tap on mobile, hover on desktop setup. @sskhandek thoughts?

**Comment by redsn0w422** [comment]
I like the tap/hover as well

**Comment by sskhandek** [comment]
Yeah that works just fine.
