### ISSUE TITLE
Create Job Fair Subpage

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#92]
located in jobfair/index.html

A small page that gives info about the job fair. Things we need: 
- a title
- a small description
- a list of the companies attending
- the most updated job fair map

**Comment by sskhandek** [comment]
@redsn0w422 how's your progress looking on the startup fair? I want to make the views decently consistent between the two pages, and simon will be getting started on the job fair page

**Comment by redsn0w422** [comment]
@bluedrops do you want to design the layout together so we're on the same page?

**Comment by bluedrops** [comment]
sure, sounds good to me
