### ISSUE TITLE
Create startupfair subpage

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#93]
located in startupfair/index.html  A small page that gives info about the startup fair. Things we need: 
- a title 
- a small description 
- a list of the companies attending 
- the most updated job fair map

**Comment by redsn0w422** [comment]
I can tackle this today and tomorrow, is the job fair map and list of companies finalized?

**Comment by sskhandek** [comment]
@tyler-thetyrant can you hand off whatever maps we have currently?

**Comment by tyler-thetyrant** [comment]
![roughdraftlayout](https://cloud.githubusercontent.com/assets/12504517/18256438/0d1a49f4-737b-11e6-903c-fb3d50e61420.png)

@sskhandek 
Ryan sent this to me this morning. This is just a draft for the company placement. He'll add the logos later.

**Comment by sskhandek** [comment]
@redsn0w422 Use that for now, the page won't be linkable or anything. You can use the description from last year's website for the startup fair

**Comment by tyler-thetyrant** [comment]
![startup](https://cloud.githubusercontent.com/assets/12504517/18324134/78b8510c-7500-11e6-8f7f-2c6efada919c.png)

@sskhandek @redsn0w422

**Comment by tyler-thetyrant** [comment]
@sskhandek if not enough company signs up, gonna ask either vincent or vivian to erase the extra lines

**Comment by tyler-thetyrant** [comment]
@sameetandpotatoes will take this.
cc: @redsn0w422

**Comment by sskhandek** [comment]
@tyler-thetyrant, @redsn0w422 is assigned to this and almost done with it. I'd rather @sameetandpotatoes work on another issue

**Comment by tyler-thetyrant** [comment]
Updated:
![startup](https://cloud.githubusercontent.com/assets/12504517/18441635/647cf00e-78d3-11e6-8fd7-cd46f24ed2e8.png)

@sskhandek @redsn0w422

**Comment by tyler-thetyrant** [comment]
![startup](https://cloud.githubusercontent.com/assets/12504517/18456197/b1efc46a-7914-11e6-90a1-850629f7dd24.png)

![nylas](https://cloud.githubusercontent.com/assets/12504517/18456198/b70f1388-7914-11e6-923b-a0c538aa5d77.jpg)

@redsn0w422
