### ISSUE TITLE
Northern Trust logo needs to be bigger

### ISSUE THREAD

**Issue by sskhandek** [acm-uiuc/rp2016#97]

**Comment by sskhandek** [comment]
<img width="972" alt="screen shot 2016-09-01 at 8 24 45 pm" src="https://cloud.githubusercontent.com/assets/5349493/18189614/231ca900-7082-11e6-9f4c-52fd5948a640.png">

Also its kinda stretched

**Comment by sskhandek** [comment]
Actually, I put in a better version, but the background is not transparent. we need some good editing to put a transparent background in

**Comment by bluedrops** [comment]
^ done and pr'd <3
