### ISSUE TITLE
Speaker Cards aren't centered

### ISSUE THREAD

**Issue by redsn0w422** [acm-uiuc/rp2016#98]
![image](https://cloud.githubusercontent.com/assets/3170794/18175193/0c8dc2e2-7036-11e6-8130-15040c07865a.png)

**Comment by sskhandek** [comment]
@redsn0w422 The line "width: calc(33% - 3%);" which is line 403 of the current master is affecting this.

**Comment by redsn0w422** [comment]
Thanks - I updated the PR.
